import { pluginPrimaryColor } from '../assets/icons';

/**
 *
 * DO NOT EDIT THIS FILE!
 * This is a copy of the component of pluginui\src\scripts\components\Loader.js
 *
 * It returns a loading animation if the `isloading` prop is true, otherwise it returns a message saying there are no more entries
 *
 *
 * @param {Object}  props                The loader color
 * @param {boolean} props.isLoading      if is loading
 * @param {number}  props.size           The loader size
 * @param {string}  props.colorPrimary   The loader primary color
 * @param {string}  props.colorSecondary The loader secondary color
 *
 * @param           props.animationSpeed
 * @return {JSX} A function that returns a component
 */
export const Loader = ( {
	isLoading,
	size = 40,
	animationSpeed = 500,
	colorPrimary = pluginPrimaryColor,
	colorSecondary = 'var(--wp--preset--color--vivid-cyan-blue)',
} ) => {
	return isLoading ? (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			viewBox={ '0 0 40 40' }
			style={ {
				width: size + 'px',
				height: size + 'px',
				fill: colorPrimary,
			} }
		>
			<path
				fill={ colorPrimary }
				d="M20.2 5.17a14.95 14.95 0 1 0 0 29.9 14.95 14.95 0 0 0 0-29.9zm0 26.58a11.63 11.63 0 1 1 0-23.27 11.63 11.63 0 0 1 0 23.27z"
			/>
			<path
				fill={ colorSecondary }
				d="m12.29 11.3-2.24-2.44A14.85 14.85 0 0 0 5.9 15.4l3.16.99a11.57 11.57 0 0 1 3.23-5.08z"
			>
				<animateTransform
					attributeType="xml"
					attributeName="transform"
					type="rotate"
					dur={ animationSpeed + 'ms' }
					from="0 20 20"
					to="360 20 20"
					repeatCount="indefinite"
				/>
			</path>
		</svg>
	) : null;
};
